name: Continuous Integration MacOS

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [
            14.1.x,
            14.14.x,
            14.x,

            15.0.0,
            15.x,

            16.0.0,
            16.x,

            17.0.0,
            17.x,

            18.0.0,
            18.x,
            
            20.0.0,
            20.x,
          ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
      - run: npm -v

      - run: npm ci
      - run: npm run test