name: Continuous Integration MacOS

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.0.0, 16.x, 18.0.0, 18.x, 20.0.0, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node -v
      - run: npm -v

      - run: npm ci
      - run: npm run test
